/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/coding_question_attempts": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.coding_question_attempts.id"];
          user_id?: parameters["rowFilter.coding_question_attempts.user_id"];
          question_id?: parameters["rowFilter.coding_question_attempts.question_id"];
          submitted_at?: parameters["rowFilter.coding_question_attempts.submitted_at"];
          is_success?: parameters["rowFilter.coding_question_attempts.is_success"];
          user_code?: parameters["rowFilter.coding_question_attempts.user_code"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["coding_question_attempts"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** coding_question_attempts */
          coding_question_attempts?: definitions["coding_question_attempts"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.coding_question_attempts.id"];
          user_id?: parameters["rowFilter.coding_question_attempts.user_id"];
          question_id?: parameters["rowFilter.coding_question_attempts.question_id"];
          submitted_at?: parameters["rowFilter.coding_question_attempts.submitted_at"];
          is_success?: parameters["rowFilter.coding_question_attempts.is_success"];
          user_code?: parameters["rowFilter.coding_question_attempts.user_code"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.coding_question_attempts.id"];
          user_id?: parameters["rowFilter.coding_question_attempts.user_id"];
          question_id?: parameters["rowFilter.coding_question_attempts.question_id"];
          submitted_at?: parameters["rowFilter.coding_question_attempts.submitted_at"];
          is_success?: parameters["rowFilter.coding_question_attempts.is_success"];
          user_code?: parameters["rowFilter.coding_question_attempts.user_code"];
        };
        body: {
          /** coding_question_attempts */
          coding_question_attempts?: definitions["coding_question_attempts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/coding_question_solutions": {
    get: {
      parameters: {
        query: {
          qid?: parameters["rowFilter.coding_question_solutions.qid"];
          solution_code?: parameters["rowFilter.coding_question_solutions.solution_code"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["coding_question_solutions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** coding_question_solutions */
          coding_question_solutions?: definitions["coding_question_solutions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          qid?: parameters["rowFilter.coding_question_solutions.qid"];
          solution_code?: parameters["rowFilter.coding_question_solutions.solution_code"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          qid?: parameters["rowFilter.coding_question_solutions.qid"];
          solution_code?: parameters["rowFilter.coding_question_solutions.solution_code"];
        };
        body: {
          /** coding_question_solutions */
          coding_question_solutions?: definitions["coding_question_solutions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/coding_questions": {
    get: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.coding_questions.created_at"];
          starter_code?: parameters["rowFilter.coding_questions.starter_code"];
          test_code?: parameters["rowFilter.coding_questions.test_code"];
          text_markdown?: parameters["rowFilter.coding_questions.text_markdown"];
          title?: parameters["rowFilter.coding_questions.title"];
          updated_at?: parameters["rowFilter.coding_questions.updated_at"];
          id?: parameters["rowFilter.coding_questions.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["coding_questions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** coding_questions */
          coding_questions?: definitions["coding_questions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.coding_questions.created_at"];
          starter_code?: parameters["rowFilter.coding_questions.starter_code"];
          test_code?: parameters["rowFilter.coding_questions.test_code"];
          text_markdown?: parameters["rowFilter.coding_questions.text_markdown"];
          title?: parameters["rowFilter.coding_questions.title"];
          updated_at?: parameters["rowFilter.coding_questions.updated_at"];
          id?: parameters["rowFilter.coding_questions.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.coding_questions.created_at"];
          starter_code?: parameters["rowFilter.coding_questions.starter_code"];
          test_code?: parameters["rowFilter.coding_questions.test_code"];
          text_markdown?: parameters["rowFilter.coding_questions.text_markdown"];
          title?: parameters["rowFilter.coding_questions.title"];
          updated_at?: parameters["rowFilter.coding_questions.updated_at"];
          id?: parameters["rowFilter.coding_questions.id"];
        };
        body: {
          /** coding_questions */
          coding_questions?: definitions["coding_questions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          display_name?: parameters["rowFilter.profiles.display_name"];
          email?: parameters["rowFilter.profiles.email"];
          /** A user's role for role-based access control */
          roles?: parameters["rowFilter.profiles.roles"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          display_name?: parameters["rowFilter.profiles.display_name"];
          email?: parameters["rowFilter.profiles.email"];
          /** A user's role for role-based access control */
          roles?: parameters["rowFilter.profiles.roles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          display_name?: parameters["rowFilter.profiles.display_name"];
          email?: parameters["rowFilter.profiles.email"];
          /** A user's role for role-based access control */
          roles?: parameters["rowFilter.profiles.roles"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/generate_uid": {
    post: {
      parameters: {
        body: {
          args: {
            size: number;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/create_profile_for_new_user": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  coding_question_attempts: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    user_id: string;
    /**
     * Note:
     * This is a Foreign Key to `coding_questions.id`.<fk table='coding_questions' column='id'/>
     */
    question_id: string;
    submitted_at: string;
    is_success: boolean;
    user_code?: string;
  };
  coding_question_solutions: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `coding_questions.id`.<fk table='coding_questions' column='id'/>
     */
    qid: string;
    solution_code?: string;
  };
  coding_questions: {
    created_at?: string;
    starter_code?: string;
    test_code?: string;
    text_markdown?: string;
    title?: string;
    updated_at?: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
  };
  profiles: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    updated_at?: string;
    display_name?: string;
    email?: string;
    /** A user's role for role-based access control */
    roles?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** coding_question_attempts */
  "body.coding_question_attempts": definitions["coding_question_attempts"];
  "rowFilter.coding_question_attempts.id": string;
  "rowFilter.coding_question_attempts.user_id": string;
  "rowFilter.coding_question_attempts.question_id": string;
  "rowFilter.coding_question_attempts.submitted_at": string;
  "rowFilter.coding_question_attempts.is_success": string;
  "rowFilter.coding_question_attempts.user_code": string;
  /** coding_question_solutions */
  "body.coding_question_solutions": definitions["coding_question_solutions"];
  "rowFilter.coding_question_solutions.qid": string;
  "rowFilter.coding_question_solutions.solution_code": string;
  /** coding_questions */
  "body.coding_questions": definitions["coding_questions"];
  "rowFilter.coding_questions.created_at": string;
  "rowFilter.coding_questions.starter_code": string;
  "rowFilter.coding_questions.test_code": string;
  "rowFilter.coding_questions.text_markdown": string;
  "rowFilter.coding_questions.title": string;
  "rowFilter.coding_questions.updated_at": string;
  "rowFilter.coding_questions.id": string;
  /** profiles */
  "body.profiles": definitions["profiles"];
  "rowFilter.profiles.id": string;
  "rowFilter.profiles.updated_at": string;
  "rowFilter.profiles.display_name": string;
  "rowFilter.profiles.email": string;
  /** A user's role for role-based access control */
  "rowFilter.profiles.roles": string;
}

export interface operations {}

export interface external {}
